version: "3.7"
services:
  api:
    image: mrzzy/np_web_folio_api:develop
    build:
      context: .
      dockerfile: ./folio/Dockerfile
      target: develop
    user: "${UID}:${GID}"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    ports:
      - "5000:5000"
    volumes:
      - ".:/src"
    depends_on:
      - db
  db:
    image: mrzzy/np_web_folio_db
    build: 
      context: ./db
      args:
        - "SA_PASSWORD=${DB_PASSWORD}"
    ports:
      - "1433:1433"
