version: "3.7"
services:
  db:
    image: mrzzy/np_web_folio_db
    build: 
      context: ./db
      args:
        - "SA_PASSWORD=${DB_PASSWORD}"
    ports:
      - "1433:1433"

  api:
    image: mrzzy/np_web_folio_api:develop
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PROJECT_NAME: "folio"
      target: develop
    user: "${UID}:${GID}"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    ports:
      - "5000:5000"
    volumes:
      - ".:/src"
    depends_on:
      - db
      
  ui:
    image: mrzzy/np_web_folio_ui:develop
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PROJECT_NAME: "folio_ui"
      target: develop
    user: "${UID}:${GID}"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    ports:
      - "5001:5001"
    volumes:
      - ".:/src"
    depends_on:
      - db
